name: Growables
main: io.github.anjoismysign.growables.Growables
version: ${project.version}
api-version: 1.21.4
depend: [ BlobLib ]
commands:
  growables:
    description: base command
    aliases: [ grow ]